apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
  namespace: reddit
  labels:
    app: reddit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        # image: 734468801857.dkr.ecr.us-east-1.amazonaws.com/redit:1
        image: 734468801857.dkr.ecr.us-east-1.amazonaws.com/redit:49
        ports:
        - containerPort: 3000
        env:
        - name: FIREBASE_API_KEY
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: apiKey
        - name: FIREBASE_AUTH_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: authDomain
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: projectId
        - name: FIREBASE_STORAGE_BUCKET
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: storageBucket
        - name: FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: messagingSenderId
        - name: FIREBASE_APP_ID
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: appId
        - name: FIREBASE_MEASUREMENT_ID
          valueFrom:
            configMapKeyRef:
              name: firebase-config
              key: measurementId
