apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
  namespace: reddit
  labels:
    app: reddit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: 734468801857.dkr.ecr.us-east-1.amazonaws.com/redit:1
        ports:
        - containerPort: 3000
