apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-ingress
  namespace: reddit
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - reddit.mostafagheta.online
    secretName: reddit-tls
  rules:
  - host: reddit.mostafagheta.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddit-service
            port:
              number: 3000
