apiVersion: v1
kind: Service
metadata:
  name: reddit-service
  namespace: reddit
  labels:
    app: reddit
spec:
  type: ClusterIP
  selector:
    app: reddit
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
